name: ci
on:
  push:
  workflow_dispatch:
jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ['ubuntu:20.04', 'ubuntu:22.04', 'ubuntu:24.04', 'debian:10', 'debian:11', 'debian:12']

    name: "PHPBinary (phpbinary-8.3.4, ${{ matrix.distro }})"
    container: "${{ matrix.distro }}"
    env:
      # https://bugs.php.net/bug.php?id=79445
      PHP_BUILD_CURL_OPTS: '--retry 3 --retry-delay 5 --connect-timeout 10'
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          set -ex
          ./install-dependencies.sh
          git clone --depth 1 https://github.com/sstephenson/bats.git
          ./bats/install.sh /usr/local

      - name: Acquire Google access token
        id: google-access-token
        uses: playeveryware/action-google-access-token@v1
        with:
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          scope: 'https://www.googleapis.com/auth/drive.readonly'
  
      - name: Download Source from Gdrive
        uses: playeveryware/action-google-drive-download@v1
        with:
          token: ${{ steps.google-access-token.outputs.token }}
          file-id: "1-o44DpIodLUByG3ILALkW2vf5MkxxbRt"
          path: "/tmp/phpbinary-8.3.4.zip"

      - name: run tests
        run: |
          set -ex
          if ! ./run-tests.sh phpbinary-8.3.4; then
            cat /tmp/php-build.*.log
            exit 1
          fi
          tar -zcf "/tmp/phpbinary-8.3.4-${{ matrix.distro }}.tar.gz" /tmp/phpbinary/bin/php
      - name: Upload PACKAGES to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: "/tmp/phpbinary-8.3.4-${{ matrix.distro }}.tar.gz"
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          folder: ${{ secrets.folderId }}
